name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    outputs:
      execution_arn: ${{ steps.trigger.outputs.execution_arn }}
    steps:
      - name: Trigger AI Review
        id: trigger
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Create properly formatted JSON payload
          payload=$(jq -n \
            --arg repo "${{ github.event.repository.name }}" \
            --arg pr_num "${{ github.event.pull_request.number }}" \
            --arg owner "${{ github.event.repository.owner.login }}" \
            --arg branch "${{ github.head_ref }}" \
            --arg author "${{ github.event.pull_request.user.login }}" \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg state "${{ github.event.pull_request.state }}" \
            --arg created_at "${{ github.event.pull_request.created_at }}" \
            --arg sha "${{ github.event.pull_request.head.sha }}" \
            '{
              repository: $repo,
              pull_request_number: $pr_num,
              owner: $owner,
              branch: $branch,
              pr_author: $author,
              pr_title: $title,
              pr_state: $state,
              pr_created_at: $created_at,
              commit_sha: $sha
            }')
          
          echo "Generated payload:"
          echo "$payload"
          
          response=$(curl -X POST "$API_ENDPOINT/review" \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "$payload")
          
          # Extract execution_arn from response
          execution_arn=$(echo "$response" | jq -r '.execution_arn')
          echo "execution_arn=$execution_arn" >> $GITHUB_OUTPUT

  check-review-status:
    needs: trigger-review
    runs-on: ubuntu-latest
    steps:
      - name: Check Review Status
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
          EXECUTION_ARN: ${{ needs.trigger-review.outputs.execution_arn }}
        run: |
          # Wait for processing
          sleep 30
          
          # Check status with retry logic
          max_retries=3
          retry_count=0
          
          while [ $retry_count -lt $max_retries ]; do
            response=$(curl -s -X GET "$API_ENDPOINT/status/$EXECUTION_ARN" \
              -H "x-api-key: $API_KEY")
            
            status=$(echo "$response" | jq -r '.status')
            
            if [ "$status" = "SUCCEEDED" ]; then
              echo "$response" | jq .
              exit 0
            elif [ "$status" = "FAILED" ]; then
              echo "Review failed" >&2
              echo "$response" | jq . >&2
              exit 1
            fi
            
            retry_count=$((retry_count+1))
            sleep 10
          done
          
          echo "Timed out waiting for review completion" >&2
          exit 1